export const translations={
 es:{home_question:'¿Qué querés grabar hoy?',home_intro:'Elegí una escena, seguí las guías y convertí uno o varios teléfonos en tu equipo de cámara.',create_scene:'Crear una escena',create_scene_help:'Empezá por una composición, diálogo o coreografía.',multi_record:'Grabar con varios teléfonos',multi_record_help:'Creá una sesión, mostrales el QR y graben juntas.',my_projects:'Mis proyectos',quick_rehearsal:'Ensayo rápido',sync_takes:'Sincronizar tomas',effects:'Efectos y sonidos',join_session:'Entrar a una sesión',join:'Entrar',privacy_local:'Privado por defecto.',privacy_local_help:'Tus grabaciones permanecen en cada teléfono hasta que decidís compartirlas o exportarlas.',settings:'Preferencias'},
 en:{home_question:'What do you want to film today?',home_intro:'Choose a scene, follow the guides, and turn one or more phones into your camera crew.',create_scene:'Create a scene',create_scene_help:'Start with a composition, dialogue, or choreography.',multi_record:'Record with multiple phones',multi_record_help:'Create a session, show the QR code, and record together.',my_projects:'My projects',quick_rehearsal:'Quick rehearsal',sync_takes:'Sync takes',effects:'Effects and sounds',join_session:'Join a session',join:'Join',privacy_local:'Private by default.',privacy_local_help:'Your recordings stay on each phone until you choose to share or export them.',settings:'Settings'},
 pt:{home_question:'O que você quer gravar hoje?',home_intro:'Escolha uma cena, siga as guias e transforme um ou vários celulares em sua equipe de câmera.',create_scene:'Criar uma cena',create_scene_help:'Comece com composição, diálogo ou coreografia.',multi_record:'Gravar com vários celulares',multi_record_help:'Crie uma sessão, mostre o QR e gravem juntos.',my_projects:'Meus projetos',quick_rehearsal:'Ensaio rápido',sync_takes:'Sincronizar tomadas',effects:'Efeitos e sons',join_session:'Entrar em uma sessão',join:'Entrar',privacy_local:'Privado por padrão.',privacy_local_help:'As gravações ficam em cada celular até você decidir compartilhar ou exportar.',settings:'Preferências'}
};
export function getPrefs(){return{language:'es',theme:'pop',format:'horizontal',subtitles:true,guideVolume:80,...JSON.parse(localStorage.getItem('uizador-preferences-v1')||'{}')}}
export function savePrefs(p){localStorage.setItem('uizador-preferences-v1',JSON.stringify({...getPrefs(),...p}));window.dispatchEvent(new CustomEvent('uizador-preferences',{detail:getPrefs()}));return getPrefs()}
export function applyLanguage(root=document){const p=getPrefs(),dict=translations[p.language]||translations.es;document.documentElement.lang=p.language;root.querySelectorAll('[data-i18n]').forEach(el=>{const v=dict[el.dataset.i18n];if(v)el.textContent=v});return p}
export function applyTheme(){const p=getPrefs();document.body.dataset.theme=p.theme;return p}
